// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DKqzszdVmd1vz7CYuH_wY3mHnZAu8rI',
    appId: '1:829235342119:web:de1c7be57d9d53264f5702',
    messagingSenderId: '829235342119',
    projectId: 'evole-e2898',
    authDomain: 'evole-e2898.firebaseapp.com',
    storageBucket: 'evole-e2898.firebasestorage.app',
    measurementId: 'G-R8JRGCB4N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf4l-cVeTIeTvP6o0nN5QIqLP7sB5LQjk',
    appId: '1:829235342119:android:990ab8d7afaa271d4f5702',
    messagingSenderId: '829235342119',
    projectId: 'evole-e2898',
    storageBucket: 'evole-e2898.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzcNEjRro8FNXZaLehds4zs7xfpIwURo',
    appId: '1:829235342119:ios:9e7e9da7125bf9274f5702',
    messagingSenderId: '829235342119',
    projectId: 'evole-e2898',
    storageBucket: 'evole-e2898.firebasestorage.app',
    iosBundleId: 'com.example.evolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzcNEjRro8FNXZaLehds4zs7xfpIwURo',
    appId: '1:829235342119:ios:9e7e9da7125bf9274f5702',
    messagingSenderId: '829235342119',
    projectId: 'evole-e2898',
    storageBucket: 'evole-e2898.firebasestorage.app',
    iosBundleId: 'com.example.evolve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DKqzszdVmd1vz7CYuH_wY3mHnZAu8rI',
    appId: '1:829235342119:web:4bfa0e017f1680684f5702',
    messagingSenderId: '829235342119',
    projectId: 'evole-e2898',
    authDomain: 'evole-e2898.firebaseapp.com',
    storageBucket: 'evole-e2898.firebasestorage.app',
    measurementId: 'G-GV7ENSC28T',
  );
}
